/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/pizza.glb 
Author: Rigsters (https://sketchfab.com/rigsters)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pizza-40d50989fec1460f8838b608d999ccd0
Title: Pizza
*/

import React, { useRef, useState, useEffect } from "react";
import { motion } from "framer-motion";
import { useGLTF } from "@react-three/drei";

const getPizzaScale = () => {
  if (window.innerWidth < 640) return 0.4; // Small screens
  if (window.innerWidth < 1024) return 0.22; // Medium screens
  return 0.3; // Large screens
};

export function Pizza(props) {
  const { nodes, materials } = useGLTF("models/pizza.glb");
  const [scale, setScale] = useState(getPizzaScale());

  useEffect(() => {
    const handleResize = () => {
      setScale(getPizzaScale());
    };

    window.addEventListener("resize", handleResize);
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  return (
    <group
      {...props}
      dispose={null}
      scale={scale}
    >
      <group rotation={[-Math.PI / 0.44, 0.47, 0.3]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.pizza_pizza_0.geometry}
            material={materials.pizza}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.Tarelka001__0.geometry}
            material={materials.Tarelka001__0}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/pizza.glb");
