/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/sandwich.glb 
Author: alban (https://sketchfab.com/alban)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/club-sandwich-pile-82fa791d53d8483c8a35c80a6369a68a
Title: Club sandwich pile
*/

import React, { useState, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

const getSandwichScale = () => {
  if (window.innerWidth < 640) return 50; // Small screens
  if (window.innerWidth < 1024) return 55; // Medium screens
  return 50; // Large screens
};

export function Sandwich(props) {
  const { nodes, materials } = useGLTF("models/sandwich.glb");
  const [scale, setScale] = useState(getSandwichScale());

  useEffect(() => {
    const handleResize = () => {
      setScale(getSandwichScale());
    };

    window.addEventListener("resize", handleResize);
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);
  return (
    <group
      {...props}
      dispose={null}
      scale={[scale, scale, scale]}
      rotation={[Math.PI / -1, 4, -0.3]}
    >
      <group>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.sand}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.sand}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.sand}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.sand}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.sand}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.sand}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.sand}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/sandwich.glb");
